# Generated by Django 5.0.4 on 2024-04-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
