# Generated by Django 5.0.4 on 2024-04-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='heading',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
